.TH print_control 5 "4 March, 1991" "Psi Release 2.0" "\*(]D"
.SH NAME
prcntr, prup, prdup \- control printing in a Fortran 77 program

.SH SYNOPSIS
.nf
integer function prcntr(request)
character*(*) request
#include <error.h>

integer function prup(keyword)
character*(*) keyword
#include <error.h>

integer function prdup()
#include <error.h>
.fi

.SH DESCRIPTION
.LP
These Fortran
routines provide a method of specifying print options in the input.
Print options are associated with symbolic names and can be turned on or
off by the user or by the program.  A program using
these print routines can easily determine whether
a given print option is on or off.  To use these routines the program
must be linked with the Psi input parsing library (libparse.a).  The
include file, error.h, can be found in the Psi include directory.

.LP
The \fBprcntr\fP function is used to turn print options on, off, and to
determine whether or not a print option has been turned on.
Calling \fBprcntr\fP with a argument of the
form '\fBON\fP \fIoption1\fP ... \fIoptionN\fP' turns on the listed
options.  Again, a return code of EOK (defined as 0 in error.h)
indicates that the call successfully completed.
Calling \fBprcntr\fP with a argument of the
form '\fBOFF\fP \fIoption1\fP ... \fIoptionN\fP' turns off the listed
options.  In this case, a return code of EOK
indicates that the call successfully completed.  If one of the print
options was off to begin with, then that option is ignored.
Calling \fBprcntr\fP with a argument of the
form '\fBIS_ON\fP \fIoption\fP' queries the given
option.  It will return 1 if the option is on and 0 if the option is off or
unknown.

.LP
The \fBprup\fP function is used to read in user defined print options from the
input.  It reads from the \fIkeyword\fP parameter in the input.
The form of the input is a vector of print lists.
Each print list is itself a vector of the form \fB(\fP\fIcontrol
option1 ... optionN\fP\fB)\fP, where \fIcontrol\fP is either \fBON\fP
or \fBOFF\fP and each \fIoption\fP is the print option affect.  The
vectors are read from the left to the right, so the
input 
.B "((ON OPTIONX OPTIONY) (OFF OPTIONX))"
has the effect of turning \fBOPTIONX\fP off and \fBOPTIONY\fP on.

.LP
The \fBprdup\fP sets up the default user print options.  It first
calls \fBprup(':DEFAULT:PRINT')\fP and then
calls \fBprup(':\fP\fIprogram_identifier\fP\fB:PRINT')\fP.

.LP
Psi programmers should follow the convention that if the print
option \fBBRIEF\fP is turned on, then only essential information
is included in the output.

.LP
Psi programmers should not use the print option \fBKEYWORD\fP.
This is reserved for use by the input parsing library.

